kind: Service
apiVersion: v1
metadata:
  name: "es"
spec:
  selector:
    escluster: "es"
  ports:
    - name: "ext-http"
      protocol: "TCP"
      port: 2113
      targetPort: 2113
    - name: "ext-tcp"
      protocol: "TCP"
      port: 1112
      targetPort: 1112
  type: LoadBalancer
