kind: Service
apiVersion: v1
metadata:
  name: "es"
spec:
  selector:
    escluster: "es"
  ports:
  - name: 'internal-http'
    protocol: TCP
    port: 2113
    targetPort: 2113
  - name: 'external-http'
    protocol: TCP
    port: 2114
    targetPort: 2114
  - name: 'external-tcp'
    protocol: TCP
    port: 1113
    targetPort: 1113
  - name: 'internal-tcp'
    protocol: TCP
    port: 1112
    targetPort: 1112
  clusterIP : None
---
kind: Service
apiVersion: v1
metadata:
  name: "es-front"
spec:
  selector:
    escluster: "es"
  ports:
    - name: "ext-http"
      protocol: "TCP"
      port: 2113
      targetPort: 2113
  type: LoadBalancer
